modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="emi_loot"
version="${version}"
displayName="EMI Loot"
authors="fzzyhmstrs, lxly9 (art), unilock (porting)"
description='''Plugin for EMI that shows chest loot, block drops, mob drops, and gameplay loot like fishing.'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="emi_loot.mixins.json"

[[dependencies.emi_loot]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.emi_loot]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
