modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="emi_loot"
version="${version}"
displayName="EMI Loot"
authors="fzzyhmstrs, lxly9 (art), unilock (porting)"
description='''Plugin for EMI that shows chest loot, block drops, mob drops, and gameplay loot like fishing.'''

[[mixins]]
config="emi_loot.mixins.json"

[[dependencies.emi_loot]]
    modId="neoforge"
    type="required"
    versionRange="[20.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emi_loot]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.3,)"
    ordering="NONE"
    side="BOTH"
